### ISSUE TITLE
How to load custom dataset

### ISSUE THREAD

**Issue by Riroaki** [thunlp/OpenAttack#111]
Hi, I'm wondering how I could load a dataset and turn it into the format which `OpenAttack.DataManager.loadDataset` returns in, or I should manually create some `OpenAttack.utils.dataset.DataInstance`s and modify their properties?

**Comment by a710128** [comment]
Hi Riroaki, thanks for your question. 
`OpenAttack.DataManager.loadDataset` returns a `Dataset` object, and you can create a `Dataset` like this:
```python
YOUR_DATASET = Dataset([
    DataInstance(
        x= "sentence that you want to attack",
        y=0, # groud truth label
        target=None, # attack target label (leaves None for untargeted attack)
        meta={} # other information of this data instance
    ),
    ...
])
```

**Comment by Riroaki** [comment]
Thanks, but how can the victim model access the `meta` property?

**Comment by Fanchao-Qi** [comment]
Sorry to reply to your late.
We have supported this function in our development version, and we will make the update to the master branch soon.

**Comment by Riroaki** [comment]
That's ok and I implemented it myself. Thanks for your reply! And it would be very helpful if you support this feature😊
