### ISSUE TITLE
How to deal with multi-label target?

### ISSUE THREAD

**Issue by Riroaki** [thunlp/OpenAttack#112]
What if I want to attack models on a dataset with more than 2 labels ('pos' / 'neg')? I only see models with `get_prob` function returning only probability for 2 labels.

**Comment by Riroaki** [comment]
Oh, this is not a problem as I tried multi-class dataset.

**Comment by sxhhb123** [comment]
您好，我也遇到了这个问题，想要处理多标签数据怎么办。

**Comment by sxhhb123** [comment]
Hello, I also ran into this problem, what to do if you want to deal with multi-label data.
