### ISSUE TITLE
How to perform attack in a multi-process manner?

### ISSUE THREAD

**Issue by Riroaki** [thunlp/OpenAttack#113]
The attack process is too slow. Is there any way to accelerate it or multi-process it?

**Comment by Fanchao-Qi** [comment]
Hmm, some attack method is slow indeed, especially the method that uses language model. Empirically we find that language model actually contributes little to the attack performance. So if you are using the attack method that uses language model, we recommend you removing it.

Sorry that OpenAttack does not support multi-process now. But we will consider adding this function.

**Comment by Riroaki** [comment]
Well, I implemented multiprocessing manually, though rather naive but it works.
Thanks for your reply, and I think it's necessary to **invest whether multiprocessing affects the speed of a single model**...in my case, the time cost of a single model increased when there are multiple models working simultaneously on a GPU device😂

**Comment by Fanchao-Qi** [comment]
The newest version has incorporated the support of multi-process. Thanks for your suggestion.

**Comment by zhy605420954** [comment]
> The newest version has incorporated the support of multi-process. Thanks for your suggestion.

could you please tell me how to perform attack in a multi-process manner? I couldn't find any message about it.
