### ISSUE TITLE
Potential bug in word substitution

### ISSUE THREAD

**Issue by Riroaki** [thunlp/OpenAttack#114]
I met with a crash at this line for some examples:

https://github.com/thunlp/OpenAttack/blob/637e81a9c60874ec35f923d7c62687cbd6ee3633/OpenAttack/substitutes/wordnet.py#L66

The reason behind this is when `word` is composed of only "_" characters, e.g. `word="_"`, the code would run into a `IndexError: list index out of range` exception.
So I think perform some checks before this line should avoid this problem.

**Comment by Cypredar** [comment]
Thank you for your question, we will solve this problem soon.
