### ISSUE TITLE
How to load new trained BERT model?

### ISSUE THREAD

**Issue by NoviScl** [thunlp/OpenAttack#115]
Is there any example code showing how to load my own trained BERT model (trained using Huggingface's Transformer library). I have my own BERT classifier codes as well as the model weights trained on my dataset, I can load the trained weights to initialize the model using Huggingface's codes, but how do I do that using your OpenAttack.DataManager and use it as the target model for attacking?
Some simple example would be really appreciated!

**Comment by Fanchao-Qi** [comment]
Hi. We are working on that and will release some example code soon.
