### ISSUE TITLE
Implementation Error for UAT

### ISSUE THREAD

**Issue by NoviScl** [thunlp/OpenAttack#117]
It seems that in attacker/uat.py, the __call__ function of the attacker just returns the originally initialised triggers without performing any search :o

**Comment by NoviScl** [comment]
Also, could you show how to make it work on BERT? It seems that you need to provide an embedding matrix and word2id dictionary for the method, I suspect that you need to do some adaptation to make it work for BERT.

**Comment by Cypredar** [comment]
Treggers in UAT need to be used in the following way(by calling get_triggers):
triggers = OpenAttack.attackers.UATAttacker.get_triggers(clsf, dataset, word2id=clsf.config["word2id"], embedding=clsf.config["embedding"])

Embedding and word2id for BERT is bert_classifier.word2id and bert_classifier.embedding.
