### ISSUE TITLE
New Attacker

### ISSUE THREAD

**Issue by NoviScl** [thunlp/OpenAttack#119]
Found a new attack paper: https://arxiv.org/pdf/2009.07502.pdf
Would be good to integrate it in OpenAttack

**Comment by Cypredar** [comment]
Thanks for your suggestion, we'll learn about this paper soon.

**Comment by shizhouxing** [comment]
To my knowledge, leveraging masked language model for adversarial examples has appeared earlier in https://arxiv.org/abs/1909.02560 (though word replacement only), which is missed by some recent works.

**Comment by a710128** [comment]
I closed the issue because it hasn't had any new activity in a long time. If you have a similar problem, please reopen it.
