### ISSUE TITLE
[Need helps] OpenAttack may Cause the OS reboot without any warnings

### ISSUE THREAD

**Issue by Raibows** [thunlp/OpenAttack#122]
Hi!
I met a weird bug that is the OS will reboot suddenly when trying to run the example code of OpenAttack.
Here is my environment:

- OS: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-52-generic x86_64)
- Python: 3.7.9 (Anaconda)
- OpenAttack: 1.1.1
- CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
- Mem:  64GB

It works well when running the ``demo.py`` in the root directory of OpenAttack. But will cause the OS reboot in few seconds with running below example codes:

```py
from torch import nn, optim
from torch.utils.data import DataLoader
from tqdm import tqdm
import argparse
import re
import torch
import OpenAttack as oa


if __name__ == '__main__':
        device = torch.device('cuda:0')
        print('hello?')
        victim = oa.DataManager.load("Victim.BERT.SST")
        # choose an evaluation dataset
        dataset = oa.DataManager.load("Dataset.SST.sample")

        # choose Genetic as the attacker and initialize it with default parameters
        attacker = oa.attackers.GeneticAttacker()
        # # prepare for attacking
        attack_eval = oa.attack_evals.DefaultAttackEval(attacker, victim)
        # # launch attacks and print attack results
        attack_eval.eval(dataset, visualize=True)
```

The cpuinfo shows that the cpu reaches full load soon after runing the above codes. And it will reboot in few seconds with no output, no exit codes, no warnings. Monitoring the temperature/fans/ power of CPU, there is nothing irregular. And I even try to read the kernel log(``/var/log/syslog``) to find what happend, but there is no useful messages indicating no  kernel dead messages. Seems like the server has something wrong in the power supply or hardware. It confused me for several days.

Today I try to run the cpu-stress(``s-tui`` package), the cpu also reaches full load. But it still works well after nearly 20 minutes stress-testing. it's very weird. 

Hope to get your help. Sincere thanks to you!

**Comment by Cypredar** [comment]
Thank you for your feedback. We will try to reproduce and solve this problem.

**Comment by Raibows** [comment]
I have traced the call stack and find the fatal error shall be in GeneticAttacker.perturb(*args) method in attackers/genetic.py. And there is a relation with numpy or intel mkl. It is very hard to debug to find the detailed error reason or specific line of code since there are lot of variables are random generated. 
Hope this could help you reduce the debug work. Just let me know if you need other information.

**Comment by Cypredar** [comment]
Thank you for your information and advice, but it's still hard for us to create the problem and try to resolve it. We haven't had a similar problem on our CPU, and now we're trying to find the code that might trigger the problem.

**Comment by a710128** [comment]
I closed the issue because it hasn't had any new activity in a long time. If you have a similar problem, please reopen it.
