### ISSUE TITLE
More general attack in HotFlip

### ISSUE THREAD

**Issue by ForeverZyh** [thunlp/OpenAttack#125]
I find the HotFlip attacker only supports substitution. However, in HotFlip paper, it said, "HotFlip also supports insertion and deletion operations by representing them as sequences of character substitutions." 

I find HotFlip can be generalized to almost arbitrary string transformations. In our paper, we defined a DSL for specifying a string transformation as an attack model. (https://arxiv.org/abs/2002.09579)
And I have implemented a prototype in https://github.com/ForeverZyh/A3T/blob/master/DSL/transformations.py.
However, the code is not clean and I've also used multiprocessing to speed up the adversarial training, limiting the generalizability. 

I would like to contribute to this project. If you find it is interesting, we can probably have a chat.

**Comment by Cypredar** [comment]
I am contacting the team member who replicates this part of the code. We will discuss it and reply to you after that.

**Comment by Fanchao-Qi** [comment]
In any case, we are very pleased that you are willing to contribute to this project. We can have a chat on [Slack](https://join.slack.com/t/openattack/shared_invite/zt-j4ue3rk2-btbve5W07KDaiQjkiy0Bfg).

**Comment by a710128** [comment]
I closed the issue because it hasn't had any new activity in a long time. If you have a similar problem, please reopen it.
