### ISSUE TITLE
[Need helps] Can you give a example of using JSMA (FDAttacker) to attack models 

### ISSUE THREAD

**Issue by dumpling-Eric** [thunlp/OpenAttack#130]
when i use the JSMA (FDAttacker), i have some issues, i cannot solve it for myself.
can you give a example of using JSMA (FDAttacker) to attack models like the workflow.py
thanks very much

**Comment by Cypredar** [comment]
Can you explain further the problems you have encountered? FDAttacker is used in the same manner as other Attackers; an example can be found in demo.py.

**Comment by dumpling-Eric** [comment]
Thank you for your reply. The JSMA (FDAttackers) needs the word embedding vectors, but demo.py do not provide the embedding method, word2vec or GloVe?

**Comment by Cypredar** [comment]
All the victim models we provide can use the model.embedding. If you have your own model, you need to provide an Embedding Vector yourself.

**Comment by dumpling-Eric** [comment]
thanks, the issue has been resolved.
