### ISSUE TITLE
How to load chinese datasets (LCQMC)?

### ISSUE THREAD

**Issue by hinesboy** [thunlp/OpenAttack#131]

**Comment by Cypredar** [comment]
The Chinese datasets is probably what we're going to do next. May be you can try to load your own chinese dataset in the same way we load English datasets.

**Comment by hinesboy** [comment]
Thanks, looking forward to the new version.

**Comment by Fanchao-Qi** [comment]
Now, OpenAttack 2.x has incorporated the support of multilinguality. You can use datasets in any language with the help of the datasets library of Huggingface.
Please see this [doc](https://openattack.readthedocs.io/en/latest/examples/example6.html) for more information.
