### ISSUE TITLE
Does it supports doing experiments on BERT

### ISSUE THREAD

**Issue by ghost** [thunlp/OpenAttack#132]
Hi, I notice that only NLTK tokenizer is supported in this work.
I want to know how to use this framework to do some experiments on BERT and BERT tokenizer.
Thanks!

**Comment by Cypredar** [comment]
Tokenizer involves a lot of parts, our model does not support Bert Tokenizer for the time being.Bert Classifier is already provided.

**Comment by a710128** [comment]
I closed the issue because it hasn't had any new activity in a long time. If you have a similar problem, please reopen it.
