### ISSUE TITLE
Chinese Attack?

### ISSUE THREAD

**Issue by MintForever** [thunlp/OpenAttack#147]
Hi, does your toolkit support Chinese attack? I saw that you have implemented hownet for word substitution, but there isn't any specific attacker or evaluation metric for Chinese. Thank you!

**Comment by Cypredar** [comment]
I'm sorry to reply you so late. In the dev branch, some attack modes have added Chinese option, which is to replace English word with Chinese word.The function about Chinese attack is not perfect yet, we are trying to add the content about Chinese attack. Thanks for your issue.

**Comment by Fanchao-Qi** [comment]
Now, OpenAttack 2.x has incorporated the support of multilinguality. You can use the victim models in any language with the help of the transformers library of Huggingface. We also add the adaptation to some typical attack models.
