### ISSUE TITLE
Modification rate calculation maybe incorrect 

### ISSUE THREAD

**Issue by Opdoop** [thunlp/OpenAttack#148]
https://github.com/thunlp/OpenAttack/blob/5698fe7d494d85068ccfb644d4c76b920a61082c/OpenAttack/metric/modification.py#L7

This length requirement cannot be guaranteed under sentence-level attack as paraphrase result always has a differents token length from the original. So I think the `Word Modif. Rate` in sentence-level attack maybe incorrect.

**Comment by Cypredar** [comment]
Thank you for asking, but we did not calculate the modifiability rate for sentence-level attacks. This method only applies to word-level or char-level attacks.
