### ISSUE TITLE
File server slow download speed

### ISSUE THREAD

**Issue by lethaiq** [thunlp/OpenAttack#150]
Hi,

I have difficulties downloading these two files for two attacks:
https://thunlp.oss-cn-qingdao.aliyuncs.com/TAADToolbox/GNAE.zip
https://thunlp.oss-cn-qingdao.aliyuncs.com/TAADToolbox/scpn.zip

Seems like the server is located in China and accessing from US will be slow. This will crash the zip_download.py program (I guess because of timeout). Can you please upload these two files on another location?

Thanks

**Comment by Cypredar** [comment]
Thank you for your advice. The process of solving this problem may be complicated, so we'll discuss it and get back to you later.

**Comment by a710128** [comment]
We migrated our server to Hong Kong and used CDN acceleration, you can use the following method to speed up the file download.

https://openattack.readthedocs.io/en/latest/apis/data_manager.html#OpenAttack.DataManager.enable_cdn

**Comment by lethaiq** [comment]
Tested. Worked very well.
