### ISSUE TITLE
'str' object has no attribute 'softmax'

### ISSUE THREAD

**Issue by LTEnjoy** [thunlp/OpenAttack#151]
Hi, I ran into a bug when I just copied the codes listed as simple usage:

import OpenAttack as oa
    victim = oa.DataManager.load("Victim.BERT.SST")
    print(victim)
    # choose an evaluation dataset
    dataset = oa.DataManager.load("Dataset.SST.sample")
    # choose Genetic as the attacker and initialize it with default parameters
    attacker = oa.attackers.GeneticAttacker()
    # prepare for attacking
    attack_eval = oa.attack_evals.DefaultAttackEval(attacker, victim)
    # launch attacks and print attack results
    attack_eval.eval(dataset, visualize=True)

It threw an AttributeError: 'str' object has no attribute 'softmax'
Could you tell me how to solve the problem?

**Comment by Zhaojiah** [comment]
the reason might be the tranformers' version4 upgrade,if transformers==3.0.0, everything should work fine

**Comment by LTEnjoy** [comment]
你好，关于这个问题，我通过排查已经解决了。它问题出在bert模型的return返回了多个参数而在代码中接收参数的变量个数却少于返回参数的个数。
例如bert模型返回loss、logits、attention_info，而代码中接受的参数却只有两个：
a, b = bert(```)
这会导致变量变为字符串类型（具体原因未深入研究）。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thunlp/OpenAttack"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月23日(星期二) 晚上10:14
收件人:&nbsp;"thunlp/OpenAttack"<OpenAttack@noreply.github.com&gt;;
抄送:&nbsp;"LTEnjoy"<1571607536@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thunlp/OpenAttack] 'str' object has no attribute 'softmax' (#151)





 
the reason might be the tranformers' version4 upgrade,if transformers==3.0.0, everything should work fine

**Comment by Zhaojiah** [comment]
你好，可以告知一下具体的解决方法吗？

**Comment by LTEnjoy** [comment]
我忘记是在哪个地方改的代码了，不过我记得那部分代码原本是:
_, logits = bert(```)
因为Bert模型返回的是一个命名元组，如果前面接收参数的数量少于命名元组里元素的个数的话就会出现之前那个问题。
我估计是因为transfomers更新了改变了命名元组中元素的个数所以出现了bug。
解决方法是把logits的获得方式改成：
outputs = bert(```)
logits = outputs.logits
然后就可以对logits作softmax了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thunlp/OpenAttack"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 下午5:47
收件人:&nbsp;"thunlp/OpenAttack"<OpenAttack@noreply.github.com&gt;;
抄送:&nbsp;"LTEnjoy"<1571607536@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thunlp/OpenAttack] 'str' object has no attribute 'softmax' (#151)





 
你好，可以告知一下具体的解决方法吗？

**Comment by Fanchao-Qi** [comment]
This problem has been solved in the newest version. If you still encounter the problem, please feel free to reopen it.
