### ISSUE TITLE
How to define custom processor?

### ISSUE THREAD

**Issue by dawnranger** [thunlp/OpenAttack#153]
I want to apply OpenAttack on my own dataset, but the guide of custom processor is not documented.

**Comment by Cypredar** [comment]
Thank you for your question. How to use your own dataset training in the current version is not mentioned in the documentation so far, we may improve this feature in the future. For now, you can organize your data set into a format similar to our existing data set, such as SST-dataset and add it to the data directory, and then you can apply OpenAttack on your own dataset in the same way.

**Comment by a710128** [comment]
I closed the issue because it hasn't had any new activity in a long time. If you have a similar problem, please reopen it.
