### ISSUE TITLE
Question about the implemention of Hotflip

### ISSUE THREAD

**Issue by RichengLiang** [thunlp/OpenAttack#156]
Hotflip is based on the gradient in the original papper. I used the HotflipAttacker to attack  a LSTM classifier successfully, but I found no gradient fetch process in the source code. I would like to ask whether the HotflipAttacker in the OpenAttack is consistent with the original papper? 
Looking forward to your reply and thank you.

**Comment by Cypredar** [comment]
Thank you for your question!
In the current version of OpenAttack, HotFlip only implements the word level and black box model, so there is really no gradient process. In a future update, HotFlip will be fully updated with HotFlip's gradient attack method. Thank you for your attention!

**Comment by RichengLiang** [comment]
Get it, thank you!
