### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by HOERAIN** [thunlp/OpenAttack#178]
Hi, I ran into a bug when I just copied the codes listed as simple usage:

import OpenAttack as oa
victim = oa.DataManager.load("Victim.BERT.SST")
# choose an evaluation dataset
dataset = oa.DataManager.load("Dataset.SST.sample")
# choose TextFooler as the attacker and initialize it with default parameters
attacker = oa.attackers.TextFoolerAttacker()
# prepare for attacking
attack_eval = oa.attack_evals.DefaultAttackEval(attacker, victim)
# launch attacks and print attack results
attack_eval.eval(dataset, visualize=True)

It threw an tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'SentencepieceOp' in binary running on DESKTOP-4S1SUPC. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

Could you tell me how to solve the problem?

**Comment by Fanchao-Qi** [comment]
This problem has been solved in the newest version. If you still encounter the problem, you can reopen this issue.
