### ISSUE TITLE
workflow更改数据集和攻击模型后的问题

### ISSUE THREAD

**Issue by marsssser** [thunlp/OpenAttack#211]
有一个问题想请教一下，在跑workflow这个代码时，做了以下更改，将数据集换成BiLSTM.IMDB,攻击模型换成TEXTBUGGER，“x”:x["text"]；但出现TypeError错误。如附件中图所示。请问怎么进行调试，谢谢！
![1](https://user-images.githubusercontent.com/39151991/121990442-65d0b380-cdd0-11eb-93ad-f4e5628a21ec.png)
![2](https://user-images.githubusercontent.com/39151991/121990452-6701e080-cdd0-11eb-9d58-71d29af62412.png)

**Comment by Fanchao-Qi** [comment]
你好，请尝试最新版本(v2.1.0)是否还存在此问题，可参考[此样例](https://github.com/thunlp/OpenAttack/blob/v2.1.0/examples/custom_dataset.py)。
如仍有问题请重开此issue。
