### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by HOERAIN** [thunlp/OpenAttack#212]
Hi, After I upgraded OpenAttack to the latest version, 2.0.1, I still encountered this error. (tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'SentencepieceOp' in binary running on DESKTOP-4S1SUPC. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.)

I found that it only occurs in the TextFooler attack method, and it usually works under other attack methods.

Hope to get your help. Sincere thanks to you!

**Comment by IMUwangyihao** [comment]
I also encountered the same problem

**Comment by IMUwangyihao** [comment]
（tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'SentencepieceOp' in binary running on DESKTOP-P7DLHK5. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.）

**Comment by a710128** [comment]
I found out a solution that may help. tensorflow/hub#463
