### ISSUE TITLE
How to handle inputs consisting of sentence pairs?

### ISSUE THREAD

**Issue by begab** [thunlp/OpenAttack#214]
Hi,
I tried attacking a victim model for SNLI with inputs being pairs of sentences. The  underlying HuggingfaceClassifier expects a string as input, hence I am wondering what is the expected way of handling sentence boundary in this situation.
I tried including a [SEP] token at the sentence boundary, but this resulted in the token being attacked sometimes, which seems to be an undesired attack.
Or a simple concatenation of the premise and hypothesis sentences should do the job without indicating the boundaries between the sentences?
Thanks for the help in advance.

**Comment by a710128** [comment]
We added an example. See `examples/nli_attack.py` .
