### ISSUE TITLE
Support for multilanguage attack?

### ISSUE THREAD

**Issue by khieu** [thunlp/OpenAttack#215]
OpenAttack seems like a very versatile attacking framework. I wonder if the module has any support for non-English attack? For example, if I want to attack a French/Spanish/German model, is there a tutorial for such scenario? Really appreciate any help !

**Comment by a710128** [comment]
We do not currently have a detailed document describing how to add new languages. 
In short, you can implement `Tokenizer`s, `Substitue`s ... for the languages you need and initialize the `Attacker` with them as arguments.

Docs for `Attacker`:  [Attackers API](https://openattack.readthedocs.io/en/latest/apis/attacker.html#classificationattacker)

See code in `OpenAttack/text_process/` may help you.
