### ISSUE TITLE
Filtering words (to ignore during perturbations) shouldn't be case sensitive

### ISSUE THREAD

**Issue by lethaiq** [thunlp/OpenAttack#223]
In textbugger attack, when filtering words, the current word should be lowered case first.

`if word in self.filter_words:` => `if word.lower() in self.filter_words:`

There might be other places that need to be fixed too.

BTW, Thanks for great updates!

**Comment by Fanchao-Qi** [comment]
Thanks for pointing out this problem and we will fix it soon.
BTW, we are very happy that you like the updates.

**Comment by cgq15** [comment]
Fixed in #237
