### ISSUE TITLE
I wonder if there are other victim models

### ISSUE THREAD

**Issue by maosuk** [thunlp/OpenAttack#224]
All can i use are in openattack/data/victim_xxx.py ? can i import other pretrained victim model such as bert-base-chinese?

**Comment by Fanchao-Qi** [comment]
You can use any model as the victim model. [This example code](https://github.com/thunlp/OpenAttack/blob/master/examples/transformer.py) shows how to use BERT fine-tuned on SST-2 from Transformers as the victim model, and [this one](https://github.com/thunlp/OpenAttack/blob/master/examples/custom_victim.py) shows how to use your own model as the victim.
