### ISSUE TITLE
[Need help] Could you please give samples for customizing the get_grad and get_embeddings of the victim?

### ISSUE THREAD

**Issue by NingNing-C** [thunlp/OpenAttack#241]
I want to customize a victim model and use the FD attacker to attack, but it requires the get_grad() and get_embeddings(). I have no idea of what the outputs of those functions are expected, could you kindly give an example?

**Comment by a710128** [comment]
https://github.com/thunlp/OpenAttack/blob/bfedfa74f37c69db6d7092d9cc61822ee324919d/OpenAttack/victim/classifiers/transformers.py#L88-L166

**Comment by NingNing-C** [comment]
Thanks for replying, I have already checked this, but I don't quite understand how it works. The self.curr_embedding was assigned to None before, how it got values afterwards? Thanks a lot!

**Comment by a710128** [comment]
We registered a forward hook to get the output of embedding layer.

https://github.com/thunlp/OpenAttack/blob/bfedfa74f37c69db6d7092d9cc61822ee324919d/OpenAttack/victim/classifiers/transformers.py#L51

**Comment by NingNing-C** [comment]
Thanks a lot! I have figured it out.
