### ISSUE TITLE
关于文本攻击应用到关系抽取任务中

### ISSUE THREAD

**Issue by Youoo1** [thunlp/OpenAttack#242]
您好，我想观察将文本攻击应用到关系抽取任务时产生的对抗样本。请问在自定义模型和自定义数据集中应该如何加入啊？我在myclssifier()中加入自己的模型之后？在nltk中也没有我需要的模型啊?困在此处无法自拔.....请大佬们方便的时候解答。

**Comment by cgq15** [comment]
您好，如果您想攻击自定义模型，请参考`custom_victim`中的设定，将您训练好的模型设为`self.model`
