### ISSUE TITLE
SSL Certificate Verify Failed

### ISSUE THREAD

**Issue by sergiostef25** [thunlp/OpenAttack#247]
When i am about to run an attack and it comes to upload the attack method `attacker = oa.attackers.SCPNAttacker()` this error show up and i cannot perform anything: `<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>`
This happens with every attack or victim model.

**Comment by dlramirez2** [comment]
Same problem here. I have tried to update certifi and go a fresh install but no success.

**Comment by xiaowanzi123good** [comment]
This decorator can bypass SSL verification
```python
from contextlib import contextmanager


@contextmanager
def no_ssl_verify():
    import ssl
    from urllib import request

    try:
        request.urlopen.__kwdefaults__.update({'context': ssl.SSLContext()})
        yield
    finally:
        request.urlopen.__kwdefaults__.update({'context': None})

```

So when you need to download some datasets, you can do like this:

```python
    with no_ssl_verify():
        attacker = oa.attackers.SCPNAttacker()
```

**Comment by karakoo** [comment]
> This decorator can bypass SSL verification
> 
> ```python
> from contextlib import contextmanager
> 
> 
> @contextmanager
> def no_ssl_verify():
>     import ssl
>     from urllib import request
> 
>     try:
>         request.urlopen.__kwdefaults__.update({'context': ssl.SSLContext()})
>         yield
>     finally:
>         request.urlopen.__kwdefaults__.update({'context': None})
> ```
> 
> So when you need to download some datasets, you can do like this:
> 
> ```python
>     with no_ssl_verify():
>         attacker = oa.attackers.SCPNAttacker()
> ```

It's working!

**Comment by sergiostef25** [comment]
> This decorator can bypass SSL verification
> 
> ```python
> from contextlib import contextmanager
> 
> 
> @contextmanager
> def no_ssl_verify():
>     import ssl
>     from urllib import request
> 
>     try:
>         request.urlopen.__kwdefaults__.update({'context': ssl.SSLContext()})
>         yield
>     finally:
>         request.urlopen.__kwdefaults__.update({'context': None})
> ```
> 
> So when you need to download some datasets, you can do like this:
> 
> ```python
>     with no_ssl_verify():
>         attacker = oa.attackers.SCPNAttacker()
> ```

Thanks a lot!

**Comment by ArJone-cyh** [comment]
你好使用了上述装饰器后数据集可以下载下来但似乎出现了新的问题，具体来说貌似验证攻击时会出错data中会存储train
![image](https://user-images.githubusercontent.com/65947359/200744976-aba8aa59-78b9-4fa0-bcd1-d91ba162c764.png)
![image](https://user-images.githubusercontent.com/65947359/200745190-e02ffd2c-2790-4c9a-9dc4-fb431be908fb.png)
这是源码
![image](https://user-images.githubusercontent.com/65947359/200745501-ffca8f66-2807-4af2-89be-8c24af624cec.png)
![image](https://user-images.githubusercontent.com/65947359/200745470-c5824455-374d-490d-b460-0d834de4496b.png)

**Comment by paullintilhac** [comment]
would it be possible to renew the ssl cert? seems like it would be easy.

**Comment by lanaier** [comment]
I have the same problem. How did you solve it
