### ISSUE TITLE
运行程序问题请教

### ISSUE THREAD

**Issue by 1066118757** [thunlp/OpenAttack#248]
您好，我想咨询一下，我在本地Jupyter中运行OpenAttack程序的例子，一直出现以下问题
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>
下载模型都不是很正常，可能是什么原因呢？谢谢

**Comment by Hongcheng-Gao** [comment]
你可以尝试取消服务器证书验证。
例如，取消全局影响服务器证书验证功能，操作如下：

在文件开始部分，加入如下代码：

```
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
```
