### ISSUE TITLE
能否应用到其他nlp任务中

### ISSUE THREAD

**Issue by sxhhb123** [thunlp/OpenAttack#250]
作者您好，这个攻击包可以应用到命名实体识别任务中吗，还是只可以用于文本分类任务中。

**Comment by sxhhb123** [comment]
Can it be applied to multi-label tasks?

**Comment by Hongcheng-Gao** [comment]
对于multi-label 的分类任务是没有问题的。但如果需要用到其他任务中，例如命名实体识别，目前还不能直接使用，需要修改一些源码。
