### ISSUE TITLE
运行demo.py时LanguageTool报错：language_tool_python.utils.LanguageToolError

### ISSUE THREAD

**Issue by klay6** [thunlp/OpenAttack#253]
![image](https://user-images.githubusercontent.com/109709555/180119922-07ebaa32-0667-4955-8990-14f3ff764413.png)

**Comment by DachengLi1** [comment]
Hi same here.. Have you found out the solution? Thanks!

**Comment by Ph1lister** [comment]
"pip install language_tool_python" can help

**Comment by Ph1lister** [comment]
you have a try to pip Language_Tool, and pip open_jdk
