### ISSUE TITLE
I ran python setup.py install and got this error “TypeError: a bytes-like object is required, not 'str'”, I don’t know why.

### ISSUE THREAD

**Issue by RuoyanZhao-lab** [thunlp/OpenAttack#96]

**Comment by RuoyanZhao-lab** [comment]
It is because of the python version problem, I have solved it.

**Comment by zhougr18** [comment]
You missed a command option, so the right command is "python setup.py install". You can use "pip install OpenAttack", too.

在2020-08-03 10:51:37，RuoyanZhao-labnotifications@github.com写道：

**Comment by RuoyanZhao-lab** [comment]
I encountered a new problem again,and I don’t know why.
![image](https://user-images.githubusercontent.com/59050436/89241343-30e0c580-d631-11ea-8afa-cbcbadadf76e.png)
