### ISSUE TITLE
Does it support Chinese data?

### ISSUE THREAD

**Issue by Vincent131499** [thunlp/OpenAttack#98]
Does this work support Chinese data?
Can you give some sample tutorials in Chinese

**Comment by Fanchao-Qi** [comment]
Theoretically OpenAttack supports any languages. But currently the `TextProcessor` and `Substitute` modules are mainly designed for English. We are planning to support Chinese text preprocessing and substitution search.

**Comment by Vincent131499** [comment]
Great! I hope it can be adapted to Chinese as soon as possible

**Comment by datalee** [comment]
Great! I hope it can be adapted to Chinese as soon as possible

**Comment by Fanchao-Qi** [comment]
Now, OpenAttack 2.x has incorporated the support of multilinguality. You can use datasets in any language with the help of the datasets library of Huggingface.
